/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());

    }

    @Test
    public void testRoll() {
        int[] rollsDice = Library.roll(3);
        assertEquals("number of times rolls", 3, rollsDice.length);
    }
    @Test
    public void testContainsDuplicates() {
        int[] arr = {2,5,7,6,5,4,2};
        assertTrue("There is duplicate",Library.containsDuplicates(arr));
    }

    @Test
    public void testAverage() {
        int[] arr = {66, 64, 58, 65, 71, 57, 60};
        int sum = 0;
        for(int j=0;j<arr.length;j++){
            sum = sum + arr[j];
        }
        double result = sum/arr.length;

        assertTrue("the avg is ", Library.average(arr)== result);
    }

    @Test
    public void testArrayAvg() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        int [] subArray = weeklyMonthTemperatures[2];
        int [] resultArray = Library.arrayAvg(weeklyMonthTemperatures);
        assertEquals("the lowest array  ", subArray,resultArray);
    }


}
