/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Random;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
//        int[] arr1  = {1,2,3,50,40,86,20,10};
//        System.out.println(Arrays.toString(roll(1)));
//        System.out.println(average(arr1));
//        int[] arr  = {1,2,3};
//        System.out.println(containsDublicates(arr));
//
//        int[][] weeklyMonthTemperatures = {
//                {66, 64, 58, 65, 71, 57, 60},
//                {57, 65, 65, 70, 72, 65, 51},
//                {55, 54, 60, 53, 59, 57, 61},
//                {65, 56, 55, 52, 55, 62, 57}
//        };
//
//        System.out.println(Arrays.toString(arrayAvg(weeklyMonthTemperatures)));
    }

    public static int[] roll(int n){
        Random rand = new Random();
        int[] numbers = new int[n];
        for(int i =0; i<n ; i++){
            int randomNum = rand.nextInt((6 - 1) + 1) + 1;
            numbers[i] = randomNum;
        }
        return numbers;

    }

    public static boolean containsDuplicates(int[] arr){
        boolean check = false;
        for(int i=0;i<arr.length;i++){
            for(int j=i+1;j<arr.length;j++){
                if(arr[i] == arr[j]){
                    check = true;
                }
            }
        }
        return check;
    }

    public static double average(int[] arr){
        int avg = 0;
        for(int j=0;j<arr.length;j++){
           avg = avg + arr[j];
        }
        double result = avg/arr.length;
        return result;
    }

    public static int[] arrayAvg(int[][] arr){
        HashMap<Integer, Double> array = new HashMap<>();
        for(int i =0;i<arr.length;i++){
            int sum = 0;
            for(int j= 0; j<arr[i].length; j++){
                sum = sum + arr[i][j];
            }
            double result = sum/ arr[i].length;
            System.out.println(result);
            array.put(i, result);
        }

        double min = array.get(0);
        int key = 0;
        for(int k =1; k<array.size();k++){
            if(min> array.get(k)){
                min = array.get(k);
                key = k;
            }
        }
        return arr[key];

    }
}
