/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
//        Restaurant r = new Restaurant("osama", 8, 5);
//        //Review re = new Review("osama", "osama");
//
//
//        r.addReview("Hello my name is Osama And I review your restaurant ", "osama",3);
//
//        System.out.println(r.toString());

        Shop s = new Shop("rhtert","35g245", 5);
        System.out.println(s.toString());

        Theater t = new Theater("Osama");

        t.addMovie("Hitman");
        t.addMovie("X man");
        t.addMovie("Baki");
        t.addMovie("Hitman");
        t.removeMovie("Hitman");

        System.out.println(t.toString());


    }
}
