/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {

        Restaurant r = new Restaurant("SunShine","20");

        System.out.println(r.toString());

        Review re = new Review("the restaurant is good","Osama", 4);

        System.out.println(re.toString());

        r.addReview(re);
        System.out.println(r.toString());




    }
}
