/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant r = new Restaurant("osama", 8, 5);
        //Review re = new Review("osama", "osama");


        r.addReview("Hello my name is Osama And I review your restaurant ", "osama",3);

        System.out.println(r.toString());

    }
}
