/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {

    }

    @Test public void testRestaurant() {
        Restaurant r = new Restaurant("SunShine","20");
        String exp = "Name: SunShine, Price: 20, Rating: 0";
        assertEquals("the output is", exp,  r.toString());

    }

    @Test public void testReview() {
        Review re = new Review("the restaurant is good","Osama", 4);
        String exp = "My name is : Osama And my review : the restaurant is good I give you 4";
        assertEquals("the output is", exp,  re.toString());

    }

    @Test public void testAddReviewRestaurant() {
        Restaurant r = new Restaurant("SunShine","20");
        Review re = new Review("the restaurant is good","Osama", 4);
        r.addReview(re);
        assertEquals("the output is", 4,  r.star);

    }

    @Test public void testShop() {
        Shop s = new Shop("MD","20");
        String exp = "Name: MD, Price: 20, Rating: 0";
        assertEquals("the output is", exp,  s.toString());

    }

    @Test public void testAddReviewShop() {
        Shop s = new Shop("MD","20");
        Review re = new Review("the Shop is good","Osama", 3);
        s.addReview(re);
        assertEquals("the output is", 3,  s.star);

    }

    @Test public void testTheater() {
        Theater t = new Theater("Main Theater","20");
        String exp = "Name: City, Price: 20, Rating: 0";
        assertEquals("the output is", exp,  t.toString());

    }

    @Test public void testAddReviewTheater() {
        Theater t = new Theater("Main Theater","20");
        Review re = new Review("the Shop is good","Osama", 3);
        t.addReview(re);
        assertEquals("the output is", 3,  t.star);

    }
    @Test public void testAddMovieTheater() {
        Theater t = new Theater("Main Theater","20");
        Movie m = new Movie("Iron man");
        t.addMovie(m);
        assertTrue("the output is",  t.movies.contains(m));

    }


}
