/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;

import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testCheckLine() {
        Path p = Paths.get("./src/main/resources/gates.js");
        Path p1 = Paths.get("./src/main/resources/gates1.js");
        Path p2= Paths.get("./src/main/resources/gates2.js");
        Path p3= Paths.get("./src/main/resources/gates3.js");
        Path p4= Paths.get("./src/main/resources/gates4.js");
        Path p5= Paths.get("./src/main/resources/gates5.js");
        String test1 = App.checkLine(p);
        String test2 = App.checkLine(p1);
        String test3 = App.checkLine(p2);
        String test4 = App.checkLine(p3);
        String test5 = App.checkLine(p4);
        String test6 = App.checkLine(p5);
        String expect = "Line 3 Missing semicolon.\n" +
                "Line 5 Missing semicolon.\n" +
                "Line 11 Missing semicolon.\n" +
                "Line 13 Missing semicolon.\n" +
                "Line 15 Missing semicolon.\n" +
                "Line 26 Missing semicolon.\n" +
                "Line 28 Missing semicolon.\n" +
                "Line 32 Missing semicolon.\n" +
                "Line 36 Missing semicolon.\n" +
                "Line 40 Missing semicolon.\n" +
                "Line 41 Missing semicolon.\n" +
                "Line 50 Missing semicolon.\n" +
                "Line 51 Missing semicolon.\n" +
                "Line 59 Missing semicolon.\n" +
                "Line 60 Missing semicolon.\n" +
                "Line 61 Missing semicolon.\n" +
                "Line 62 Missing semicolon.\n" +
                "Line 64 Missing semicolon.\n" +
                "Line 70 Missing semicolon.\n" +
                "Line 71 Missing semicolon.\n" +
                "Line 72 Missing semicolon.\n" +
                "Line 73 Missing semicolon.\n" +
                "Line 74 Missing semicolon.\n" +
                "Line 76 Missing semicolon.\n" +
                "Line 77 Missing semicolon.\n" +
                "Line 78 Missing semicolon.\n" +
                "Line 79 Missing semicolon.\n" +
                "Line 80 Missing semicolon.\n" +
                "Line 82 Missing semicolon.\n" +
                "Line 83 Missing semicolon.\n" +
                "Line 84 Missing semicolon.\n" +
                "Line 85 Missing semicolon.\n" +
                "Line 86 Missing semicolon.\n" +
                "Line 88 Missing semicolon.\n" +
                "Line 89 Missing semicolon.\n" +
                "Line 90 Missing semicolon.\n" +
                "Line 91 Missing semicolon.\n" +
                "Line 92 Missing semicolon.\n" +
                "Line 94 Missing semicolon.\n" +
                "Line 95 Missing semicolon.\n" +
                "Line 96 Missing semicolon.\n" +
                "Line 97 Missing semicolon.\n" +
                "Line 98 Missing semicolon.\n" +
                "Line 99 Missing semicolon.\n" +
                "Line 100 Missing semicolon.\n" +
                "Line 101 Missing semicolon.\n";


        String expect1 = "";
        String expect2 = "Line 5 Missing semicolon.\n";
        String expect3 = "Line 13 Missing semicolon.\n" +
                "Line 32 Missing semicolon.\n" +
                "Line 40 Missing semicolon.\n";
        String expect4 = "Line 3 Missing semicolon.\n" +
                "Line 5 Missing semicolon.\n" +
                "Line 11 Missing semicolon.\n" +
                "Line 13 Missing semicolon.\n" +
                "Line 15 Missing semicolon.\n" +
                "Line 26 Missing semicolon.\n" +
                "Line 28 Missing semicolon.\n" +
                "Line 32 Missing semicolon.\n" +
                "Line 36 Missing semicolon.\n" +
                "Line 40 Missing semicolon.\n" +
                "Line 41 Missing semicolon.\n" +
                "Line 50 Missing semicolon.\n" +
                "Line 51 Missing semicolon.\n" +
                "Line 59 Missing semicolon.\n" +
                "Line 60 Missing semicolon.\n" +
                "Line 61 Missing semicolon.\n" +
                "Line 62 Missing semicolon.\n" +
                "Line 64 Missing semicolon.\n" +
                "Line 70 Missing semicolon.\n" +
                "Line 71 Missing semicolon.\n" +
                "Line 72 Missing semicolon.\n" +
                "Line 73 Missing semicolon.\n" +
                "Line 74 Missing semicolon.\n" +
                "Line 76 Missing semicolon.\n" +
                "Line 77 Missing semicolon.\n" +
                "Line 78 Missing semicolon.\n" +
                "Line 79 Missing semicolon.\n" +
                "Line 80 Missing semicolon.\n" +
                "Line 82 Missing semicolon.\n" +
                "Line 83 Missing semicolon.\n" +
                "Line 84 Missing semicolon.\n" +
                "Line 85 Missing semicolon.\n" +
                "Line 86 Missing semicolon.\n" +
                "Line 88 Missing semicolon.\n" +
                "Line 89 Missing semicolon.\n" +
                "Line 90 Missing semicolon.\n" +
                "Line 91 Missing semicolon.\n" +
                "Line 92 Missing semicolon.\n" +
                "Line 94 Missing semicolon.\n" +
                "Line 95 Missing semicolon.\n" +
                "Line 96 Missing semicolon.\n" +
                "Line 97 Missing semicolon.\n" +
                "Line 98 Missing semicolon.\n" +
                "Line 99 Missing semicolon.\n" +
                "Line 100 Missing semicolon.\n" +
                "Line 101 Missing semicolon.\n";
        String expect5 = "";
        assertEquals("Test case one", expect, test1);
        assertEquals("Test case one", expect1, test2);
        assertEquals("Test case one", expect2, test3);
        assertEquals("Test case one", expect3, test4);
        assertEquals("Test case one", expect4, test5);
        assertEquals("Test case one", expect5, test6);
    }
}
